# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lunch' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for lunch
  # Pods for test_google_signin
  pod 'GoogleSignIn'
  
  target 'lunch-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  end

  target 'lunchTests' do
    inherit! :search_paths
    # Pods for testing
  end

end